trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  resourceGroup: 'SubscriptionMR_ResourceGroup'
  logicAppName: 'demo-logicapp'
  location: 'East US'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '462ed967-4e5c-4d41-a264-58697cea3e97'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az logicapp deployment create \
        --resource-group $(resourceGroup) \
        --name $(logicAppName) \
        --location $(location) \
        --src-path $(System.DefaultWorkingDirectory)/demoapp-workflow