trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  resourceGroup: 'SubscriptionMR_ResourceGroup'
  logicAppName: 'demo-logicapp'
  location: 'East US'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '4a363a72-2f1b-4954-b847-5437c2827782'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az logicapp deployment create \
        --resource-group $(resourceGroup) \
        --name $(logicAppName) \
        --location $(location) \
        --src-path $(System.DefaultWorkingDirectory)/demoapp-workflow